Fixed tests, applied code style
usgs/neic-locator pull request #42
Opened 2020-08-13 21:02 UTC by jpatton-USGS

This PR fixes the unit tests and applies the Google code format.

2020-08-16 16:06 UTC, mguy-usgs requested changes
This looked good, and I think you left the commented out zone stats stuff mostly in (the plus and minus red and green is sometimes confusing as to the end result of the actual file) but I *think* Ray was going to add it back in, so we don't want to remove the commented out zone stat stuff if you want Ray to start with this version. So I won't merge until you confirm....

2020-08-16 16:06 UTC, mguy-usgs commented on src/main/java/gov/usgs/locator/Stepper.java
> -// import gov.usgs.locaux.ZoneStats;
Isn't Ray going to put Zone Stats back in...maybe you don't want to delete these zone stats things that are commented out...?

2020-08-17 14:08 UTC, jpatton-USGS commented on src/main/java/gov/usgs/locator/Stepper.java
> -// import gov.usgs.locaux.ZoneStats;
The code style checker (required for successful build) does not like commented out imports, it automatically nuked them when I applied the style.

2020-08-17 14:09 UTC, jpatton-USGS commented on src/main/java/gov/usgs/locator/Stepper.java
> -// import gov.usgs.locaux.ZoneStats;
anyone running gradle builds will not get a jar until the style checker is happy, so I don't see a way around it.

2020-08-18 15:53 UTC, merged